#png("inequality.vs.trust.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,1],xlab="Income Inequality",type="p",pch=20,ylab="Trust",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,1],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=60,labels="r=-0.61")
#dev.off()
#png("inequality.vs.life.expectancy.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,2],xlab="Income Inequality",type="p",pch=20,ylab="Life Expectancy",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,2],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=81,labels="r=-0.5")
#dev.off()
#png("inequality.vs.infant.mortality.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,3],xlab="Income Inequality",type="p",pch=20,ylab="Infant Mortality",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,3],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=6.5,labels="r=0.81")
#dev.off()
#png("inequality.vs.obesity.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,4],xlab="Income Inequality",type="p",pch=20,ylab="Obesity",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,4],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=28,labels="r=0.57")
#dev.off()
#png("inequality.vs.teenage.births.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,5],xlab="Income Inequality",type="p",pch=20,ylab="Teenage Births",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,5],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=40,labels="r=0.73")
#dev.off()
#png("inequality.vs.homicides.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,6],xlab="Income Inequality",type="p",pch=20,ylab="Homicides",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,6],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=50,labels="r=0.57")
#dev.off()
#png("inequality.vs.log_imprisonment.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,7],xlab="Income Inequality",type="p",pch=20,ylab="log(Imprisonment)",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,7],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=5.5,labels="r=0.68")
#dev.off()
#png("inequality.vs.drugs.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,8],xlab="Income Inequality",type="p",pch=20,ylab="Drugs Index",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,8],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=1.0,labels="r=0.65")
#dev.off()
#png("inequality.vs.calories.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,9],xlab="Income Inequality",type="p",pch=20,ylab="Calories Intake",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,9],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=2900,labels="r=0.47")
#dev.off()
#png("inequality.vs.PHexpenditure.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,10],xlab="Income Inequality",type="p",pch=20,ylab="Public Health Expenditure",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,10],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=50,labels="r=-0.54")
#dev.off()
#png("inequality.vs.child_wellbeing.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,11],xlab="Income Inequality",type="p",pch=20,ylab="Child Wellbeing",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,11],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=-0.6,labels="r=-0.61")
#dev.off()
#png("inequality.vs.foreign_aid.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,12],xlab="Income Inequality",type="p",pch=20,ylab="Foreign Aid",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,12],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=0.8,labels="r=-0.61")
#dev.off()
#png("inequality.vs.peace.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,13],xlab="Income Inequality",type="p",pch=20,ylab="Peace Index",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,13],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=2.0,labels="r=0.64")
#dev.off()
#png("inequality.vs.maternity.leave.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,14],xlab="Income Inequality",type="p",pch=20,ylab="Maternity Leave",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,14],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=50,labels="r=-0.56")
#dev.off()
#png("inequality.vs.advertising.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,15],xlab="Income Inequality",type="p",pch=20,ylab="Advertising",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,15],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=4,y=1.2,labels="r=0.72")
#dev.off()
#png("inequality.vs.social_expenditure.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,16],xlab="Income Inequality",type="p",pch=20,ylab="Social Expenditure",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,16],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=27,labels="r=-0.51")
#dev.off()
#png("inequality.vs.women_status.png",width=640,height=640)
#plot(inequality.index.2,working.data.2[,17],xlab="Income Inequality",type="p",pch=20,ylab="Women's Status",xlim=c(3,9))
#text(inequality.index.2,working.data.2[,17],labels=country.2,pos=4,offset=0.3,cex=0.5)
#text(x=8,y=1.0,labels="r=-0.43")
#dev.off()
png("inequality.vs.health_social_index.png",width=640,height=640)
plot(inequality.index.2,sum.scores.reduced,xlab="Income Inequality",ylab="Health and Social Problems Index",pch=20,ylim=c(-13,13))
text(inequality.index.2,sum.scores.reduced,labels=country.2,cex=0.5,pos=1)
text(x=5,y=8,labels="r=0.83")
dev.off()
